# Site settings
title: "Avalanche.gg"
description: "Avalanche.gg is a competitive esports team focused on Valorant, representing North America at the highest level."
url: "https://www.avalanche.gg"
baseurl: "/"  # For a sub-directory setup, specify it here
author: "Avalanche.gg Team"
# _config.yml
title: Avalanche.gg - Valorant
description: Avalanche.gg - A competitive Valorant esports community.
url: "https://yourdomain.com"  # Replace with your actual domain
baseurl: ""  # Base URL of the site (leave empty for local testing)
author:
  name: "Avalanche.gg"
  email: "contact@avalanche.gg"  # Optional

# Social Media Links
social:
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"
  tiktok: "https://www.tiktok.com/@avalancheggofficial"

# Google Analytics ID (if available)
google_analytics: "UA-XXXXX-X"
# Navigation menu items
menu:
  - name: "Home"
    link: "/"
  - name: "About Us"
    link: "/#about"
  - name: "Our Roster"
    link: "/#roster"
  - name: "Upcoming Events"
    link: "/#events"
  - name: "Join Us"
    link: "/#join"
  - name: "Contact"
    link: "/#contact"
# Site logo or favicon path (Optional)
logo: "/assets/images/logo.png"
# Footer information
footer:
  text: "&copy; 2025 Avalanche.gg. All rights reserved."
# Disqus Configuration for comments (if using)
disqus:
  shortname: "avalanchegg"
# Pagination settings (Optional)
pagination:
  enabled: true
  per_page: 10
# Optional Google Fonts
fonts:
  primary: "Orbitron, sans-serif"
  secondary: "Arial, sans-serif"
# Markdown settings (Optional)
markdown: kramdown
theme: "minimal"  # Optional: can be customized if you're using a theme for Jekyll
markdown: kramdown  # Markdown engine used by 
