firebase:
  apiKey: "YOUR_API_KEY"
  authDomain: "YOUR_PROJECT_ID.firebaseapp.com"
  projectId: "YOUR_PROJECT_ID"
  storageBucket: "YOUR_PROJECT_ID.appspot.com"
  messagingSenderId: "YOUR_SENDER_ID"
  appId: "YOUR_APP_ID"
  measurementId: "YOUR_MEASUREMENT_ID"  # Optional

admin:
  password: "admin123"  # Change the password for admin access

contact_form:
  thank_you_message: "Thank you for your message! We'll get back to you soon." # Custom thank you message after form submission
  email_notifications:
    enabled: true
    email: "admin@yourdomain.com"  # Where notifications are sent for new messages

social_links:
  tiktok: "https://www.tiktok.com/@avalancheggofficial"
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"

discord_invite: "https://discord.gg/q84K2USD"  # Discord invite link for users to join

website:
  title: "Avalanche.gg - Valorant"
  description: "Avalanche.gg is a competitive esports team focused on Valorant, bringing the best players together!"
  footer_text: "&copy; 2025 Avalanche.gg. All rights reserved."
