firebase:
  apiKey: "AIzaSyA9IaJUs4KAV3IbcapUdBjKn-57hQ4gPpo"
  authDomain: "avalanche-b78c6.firebaseapp.com"
  projectId: "avalanche-b78c6"
  storageBucket: "avalanche-b78c6.firebasestorage.app"
  messagingSenderId: "806793807458"
  appId: "1:806793807458:web:67c5655465f7f6facb733b"
  measurementId: "G-KK5GCBWLLB"

# Initialize Firebase
firebase_initialization: 
  - import: "firebase/app"
  - import: "firebase/analytics"

# Google Analytics ID (optional)
google_analytics: 'UA-XXXXX-Y'

# Markdown settings
markdown: "kramdown"
highlighter: "rouge"

# Build settings
exclude:
  - "README.md"

# Permalinks configuration
permalink: "/:year/:month/:day/:title/"

# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Navbar settings
navbar:
  home: "#home"
  about: "#about"
  roster: "#roster"
  events: "#events"
  join: "#join"
  contact: "#contact"

# Admin settings
admin_password: "846972"  # The password used in your JS script to view the admin section
messages_local_storage_key: "messages"

# SEO settings
seo:
  meta_tags:
    - property: "og:title"
      content: "Avalanche.gg - Valorant"
    - property: "og:description"
      content: "Join Avalanche.gg - the premier Valorant esports team!"
    - property: "og:image"
      content: "URL_of_your_image"
    - property: "og:url"
      content: "https://avalanche.gg"
  twitter_card:
    - name: "twitter:card"
      content: "summary_large_image"
    - name: "twitter:site"
      content: "@avalanchegg"

# Google Tag Manager (optional, if applicable)
google_tag_manager: 'GTM-XXXX'

# Contact settings
contact_email: "contact@avalanche.gg"

# Custom settings for special pages
contact_email: "contact@avalanche.gg"
