# _config.yml

title: Avalanche.gg - Valorant
description: Avalanche.gg - A competitive Valorant esports community.
url: "https://yourdomain.com"  # Replace with your actual domain
baseurl: ""  # Base URL of the site (leave empty for local testing)

author:
  name: "Avalanche.gg"
  email: "contact@avalanche.gg"  # Optional

social:
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"
  tiktok: "https://www.tiktok.com/@avalancheggofficial"

theme: "minimal"  # Optional: can be customized if you're using a theme for Jekyll
markdown: kramdown  # Markdown engine used by Jekyll

