# Basic site information
title: Avalanche.gg - Valorant
description: "Avalanche.gg - A competitive Valorant community and esports team focused on North America."
url: "https://www.avalanche.gg"  # Main site URL

# Social media links for the footer and other places
social_links:
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"
  tiktok: "https://www.tiktok.com/@avalancheggofficial"

# Navigation settings for the menu
navigation:
  - home: "/#home"
  - about: "/#about"
  - roster: "/#roster"
  - events: "/#events"
  - join: "/#join"
  - contact: "/#contact"
  - admin: "/#admin"

# Google Analytics (optional - if you are tracking visitors)
google_analytics: "UA-XXXXXXXXX-X"

# Markdown options for the site
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme settings (if you are using a Jekyll theme)
theme: "minimal"  # Replace with the theme name you are using

# Site language and locale
locale: en_US

# Plugins and other features (for Jekyll site or similar systems)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure for posts (optional)
permalink: /:title/

# Google Fonts and assets
assets:
  - "/assets/css/style.css"  # Your CSS file path
  - "/assets/js/script.js"   # Your JavaScript file path

# Contact form details
contact_email: "contact@avalanche.gg"

# Disqus (optional - for enabling comments on your site)
disqus_shortname: "avalanchegg"

# Build settings for Jekyll
build:
  incremental: true
  future: false
  safe: false

# File exclusions
exclude:
  - "*.md"   # Exclude markdown files if you're not using them for content

# Example of custom settings for specialized pages
password_protection_enabled: true
admin_password: "846972"  # This matches the password used in your JavaScript for admin access
