# _config.yml

# Site Settings
title: "Avalanche.gg - Valorant"
description: "Avalanche.gg - Valorant community and esports"
url: "https://www.avalanche.gg"
baseurl: ""  # Adjust if you are using a subdirectory

# Navigation Links
nav:
  - title: "Home"
    url: "/#home"
  - title: "About Us"
    url: "/#about"
  - title: "Our Roster"
    url: "/#roster"
  - title: "Upcoming Events"
    url: "/#events"
  - title: "Join Us"
    url: "/#join"
  - title: "Contact"
    url: "/#contact"
  - title: "Admin Only"
    url: "/#admin"

# Social Links
social:
  tiktok: "https://www.tiktok.com/@avalancheggofficial"
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"

# Footer Settings
footer:
  text: "© 2025 Avalanche.gg. All rights reserved."

# Admin Settings (for password protection)
admin_password: "846972"

