# Site settings
title: Avalanche.gg - Valorant
description: "Avalanche.gg - A competitive Valorant community and esports team focused on North America."
url: "https://www.avalanche.gg" # Base URL of your website

# Social Media Links
social_links:
  twitter: "https://x.com/avalancheggoff"
  instagram: "https://www.instagram.com/avalanche.ggofficial?igsh=ZjM3YjE4cnhjYzVu"
  tiktok: "https://www.tiktok.com/@avalancheggofficial"

# Navigation settings
navigation:
  - home: "/#home"
  - about: "/#about"
  - roster: "/#roster"
  - events: "/#events"
  - join: "/#join"
  - contact: "/#contact"
  - admin: "/#admin"

# Theme and Design settings (If you are using a Jekyll theme)
theme: "minimal"

# Google Analytics (optional)
google_analytics: "UA-XXXXXXXXX-X"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets and Files
assets:
  - "/assets/css/style.css"  # Link to your main CSS file
  - "/assets/js/script.js"   # Link to your main JS file

# Plugins (For Jekyll usage)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure (optional, if using permalinks for pages)
permalink: /:title/

# Disqus Settings (optional)
disqus_shortname: "avalanchegg"

# Site Locale (optional)
locale: en_US

# Build settings
build:
  incremental: true
  future: false
  safe: false
  exclude:
    - "*.md"   # Exclude markdown files from being processed

# URL Handling for Content Pages
exclude:
  - "README.md"
  - "LICENSE.md"

# Custom settings for special pages
contact_email: "contact@avalanche.gg"
